// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: false,
  firebase: {
    apiKey: "AIzaSyAAX1jzSN5nSH5wDbX0TipGzy-vafzYH5g",
    authDomain: "trippin-dev.firebaseapp.com",
    databaseURL: "https://trippin-dev.firebaseio.com",
    projectId: "trippin-dev",
    storageBucket: "trippin-dev.appspot.com",
    messagingSenderId: "294857167796"
  },
  version: env.npm_package_version + '-dev',
  serverUrl: '/api',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
