// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  firebase: {
    apiKey: "AIzaSyBWMlFmRyJl8Wtgvd084vn8R4MwdFR6YFY",
    authDomain: "trippin-7c934.firebaseapp.com",
    databaseURL: "https://trippin-7c934.firebaseio.com",
    projectId: "trippin-7c934",
    storageBucket: "trippin-7c934.appspot.com",
    messagingSenderId: "803067450941"
  },
  version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ]
};
